### ISSUE TITLE
stapi::refresh_ctable does not handle SQL generation errors

### ISSUE THREAD

**Issue by mutability** [flightaware/speedtables#52] opened 2016-03-17 12:06 UTC
If gen_refresh_ctable_sql returns 0 to indicate an error, refresh_ctable does not handle this and tries to execute it as SQL, which fails:

```
03/17/2016 12:05:15 speedtable refresh of airline_fleets failed: ERROR:  syntax error at or near "0"
LINE 1: 0
        ^
```

**Comment by resuna** [comment] 2016-04-03 15:31
I've got a fix for this in the stapi-fixes branch.

What was the root cause of gen_refresh_ctable_sql returning zero? I'm not seeing how that could happen without a problem elsewhere.

**Comment by mutability** [comment] 2016-04-03 16:41
The cause was #53

**Comment by resuna** [comment] 2016-04-03 19:41
Ah, OK. This should make that kind of failure easier to debug anyway.

I'll get started on #53 - that's not a use case I had ever considered.

**Comment by resuna** [comment] 2016-05-27 13:51
I have rebased the stapi-fixes branch up to master. Can you please verify that it fixes this problems so I can merge it back?

**Comment by resuna** [comment] 2016-07-11 14:40
Fixed in stapi-fixes.

**Closed by resuna** 2016-07-11 14:40 UTC
